#!/usr/bin/env python3
"""make_numbers_extra.py -- extra LaTeX macros for the SPMB abstract, read from results_leakfree.json
(pairwise stage tests, subject counts, multistage n). Usage: python make_numbers_extra.py RESULTS_DIR [trim|untrimmed]
Writes RESULTS_DIR/numbers_extra.tex (never overwrites: an existing file is renamed *.prev_<timestamp>)."""
import json, os, sys, datetime

out = sys.argv[1]; use = sys.argv[2] if len(sys.argv) > 2 else "trim"
r = json.load(open(os.path.join(out, "results_leakfree.json")))[use]
def f(v): return f"{v:.2f}"
def p(v):
    if v < 1e-3:
        m, e = f"{v:.1e}".split("e"); return f"{m}\\times 10^{{{int(e)}}}"
    return f"{v:.3f}"
L = ["% AUTO-GENERATED by make_numbers_extra.py from results_leakfree.json (" + use + ")"]
def nc(k, v): L.append(f"\\newcommand{{\\{k}}}{{{v}}}")
wd = r["within_stage_differences"]["pairwise_wilcoxon_two_sided"]
w_pairs = [wd[k]["p_holm"] for k in ["W-N1", "W-N2", "W-N3", "W-REM"]]
nc("WithinWmaxP", p(max(w_pairs)))                                  # W worse than every sleep stage
nc("WithinFriedmanP", p(r["within_stage_differences"]["friedman"]["p"]))
nc("NThreeN", r["within_by_stage"]["N3"]["n_subjects"])
cn = r["cross_night"]; cd = cn["stage_differences"]["pairwise_wilcoxon_two_sided"]
nc("NThreeNightN", cn["same_stage_by_stage"]["N3"]["n_subjects"])
nc("CnWNThreeP", p(cd["W-N3"]["p_holm"])); nc("CnNTwoNThreeP", p(cd["N2-N3"]["p_holm"]))
nc("CnFriedmanN", cn["stage_differences"]["friedman"]["n"])
ms = r["multistage"]
nc("MsN", min(ms["n_subjects_by_probe_stage"].values()))
nc("MsAllMatchP", p(ms["paired_tests_per_subject"]["multi_all5_vs_single_match"]["p_holm"]))
nc("ReMin", f'{r["reenrolment"]["augment"]["1.0"]["mean_minutes_night2_added_per_stage"]:.0f}')
path = os.path.join(out, "numbers_extra.tex")
if os.path.exists(path): os.replace(path, path + f".prev_{datetime.datetime.now():%Y%m%d_%H%M%S}")
open(path, "w").write("\n".join(L) + "\n"); print(open(path).read())
